# Generated by Django 5.2.7 on 2025-10-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Logo', max_length=100)),
                ('image', models.ImageField(upload_to='logos/')),
            ],
        ),
    ]
