# Generated by Django 5.2.7 on 2025-10-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='steps/')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='user_roles/')),
                ('button_link', models.URLField(blank=True)),
            ],
        ),
    ]
