# Generated by Django 5.2.7 on 2025-10-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stepcard_userrolecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPlanPerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gold_perks/')),
            ],
        ),
    ]
