# Generated by Django 5.2.7 on 2025-10-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_brand_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Introducing the Guest Reader Program', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='school_videos/')),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
