# Generated by Django 5.2.6 on 2025-10-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_book_bookpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founder', models.CharField(max_length=255)),
                ('distance', models.IntegerField(default=0)),
                ('video', models.FileField(upload_to='videos/')),
                ('cover_image', models.ImageField(upload_to='videos/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
